apiVersion: apps/v1
kind: Deployment

metadata:
  name: rabbitmq
  namespace: rabbitmq

spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management-alpine
          ports:
            - containerPort: 5672
              protocol: TCP
            - containerPort: 15672
              protocol: TCP

---
apiVersion: v1
kind: Service


metadata:
  name: rabbitmq-service
  namespace: rabbitmq

spec:
  selector:
    app: rabbitmq
  ports:

    - port: 5672
      name: rabbitmq
      targetPort: 5672
      protocol: TCP

    - port: 15672
      name: management
      targetPort: 15672
      protocol: TCP
